name: Build and Test ROS Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ros:noetic-robot  # Using ROS Noetic official Docker container

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  # Currently the latest stable version

    - name: Setup ROS Environment and Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-rosdep python3-pip
        rosdep update
        rosdep install --from-paths src --ignore-src -r -y
        sudo apt-get install -y libyaml-cpp-dev

    - name: Build ROS Package
      run: |
        source /opt/ros/noetic/setup.bash
        mkdir -p catkin_ws/src
        cp -R . catkin_ws/src/
        cd catkin_ws
        catkin_make

    - name: Run Tests
      run: |
        source /opt/ros/noetic/setup.bash
        cd catkin_ws
        catkin_make run_tests && catkin_test_results

