name: Build and Test ROS Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:noetic-desktop-full

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup ROS Environment and Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-rosdep python3-pip
        rosdep update
        rosdep install --from-paths src --ignore-src -r -y
        sudo apt-get install -y libyaml-cpp-dev
      shell: bash

    - name: Build ROS Package
      run: |
    	mkdir -p catkin_ws/src
    	# Find and copy all items except the catkin_ws directory
    	find . -maxdepth 1 ! -name 'catkin_ws' -exec cp -R {} catkin_ws/src/ \;
    	cd catkin_ws
    	. /opt/ros/noetic/setup.bash
    	catkin_make
      shell: bash


    - name: Run Tests
      run: |
        . /opt/ros/noetic/setup.bash
        cd catkin_ws
        catkin_make run_tests && catkin_test_results
      shell: bash

