name: Build and Test ROS Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:noetic-desktop-full

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup ROS Environment and Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-rosdep python3-pip
        if [ ! -f /etc/ros/rosdep/sources.list.d/20-default.list ]; then
          sudo rosdep init
        fi
        rosdep update
        rosdep install --from-paths src --ignore-src -r -y
        sudo apt-get install -y libyaml-cpp-dev
      shell: bash

    - name: Build ROS Package
      run: |
        source /opt/ros/noetic/setup.bash
        mkdir -p catkin_ws/src
        cp -R .

